version: 0.2

phases:
  
  pre_build:
    commands:
      - echo "Installing tools.."
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.50.4
  build:
    commands:
      - echo "Generating Dependency Reports"
      - syft ./ > syft-report.txt
      - grype ./ > grype-report.txt
      - trivy fs --format cyclonedx --output trivy-dependencies.json ./
      - trivy fs --scanners vuln --format cyclonedx --output trivy-vulnerabilities.json ./
      - trivy sbom trivy-dependencies.json > trivy-dependencies.txt
      - trivy sbom trivy-vulnerabilities.json > trivy-vulnerabilities.txt

     
artifacts:
  files:
     - syft-report.txt
     - grype-report.txt
     - trivy-dependencies.txt
     - trivy-vulnerabilities.txt
