#workflow to trigger the git pull on server to always have latest code on server

name: VulnerabiltyScanner

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  syft_scan:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v3

      - name: validate if working
        run : echo 'running on server ls'

      - name: Syft and Grype Scan
        run : |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
          syft ./ > syft-report.txt
          grype ./ > grype-report.txt

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SyftReports
          path: |
            /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/syft-report.txt
            /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/grype-report.txt
          
  trivy_scan:
    # needs: [syft_scanning]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Trivy Scan
        run : |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.50.4
          trivy fs --format cyclonedx --output trivy-dependencies.json ./
          trivy fs --scanners vuln --format cyclonedx --output trivy-vulnerabilities.json ./
          trivy sbom trivy-dependencies.json > trivy-dependencies.txt
          trivy sbom trivy-vulnerabilities.json > trivy-vulnerabilities.txt
          
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TrivyReports
          path: |
            /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/trivy-vulnerabilities.txt
            /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/trivy-dependencies.txt

          
  # post_build:
  #   needs: [build]
  #   runs-on: self-hosted
  #   steps:
  #     - name: Save artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: VulnerabilityReoprts
  #         path: |
  #           /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/syft-report.txt
  #           /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/grype-report.txt
  #           /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/trivy-vulnerabilities.json
  #           /home/ec2-user/actions-runner/_work/Conveyor-master/Conveyor-master/trivy-dependencies.json
